services:
  orders-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: dolcelina-orders-microservice-dev
    ports:
      - "3204:3204"
      - "8231:8231"
    environment:
      NODE_ENV: development
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - .:/app
      - /app/node_modules
      - shared-tokens:/app/shared-tokens
    command: >
      sh -c "yarn install --frozen-lockfile
      && yarn start"
    networks:
      - ms-network

networks:
  ms-network:
    external: true

volumes:
  shared-tokens:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ${PROJECT_DOCKER_SHARED_ROUTE}
